[build]
  publish = "/"

[[redirects]]
  from = "/trinasolarnews"
  to = "/trinasolarnews/"
  status = 301

[[headers]]
  for = "/trinasolarnews/*.json"
  [headers.values]
    Cache-Control = "no-store, must-revalidate"
    Content-Type = "application/json; charset=utf-8"

[[headers]]
  for = "/trinasolarnews/"
  [headers.values]
    Cache-Control = "no-store, must-revalidate"
